services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      - ./laravel/.env
    volumes:
      - mysqldata:/var/lib/mysql
    ports: 
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "$$MYSQL_USER", "--password=$$MYSQL_PASSWORD"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - ./laravel:/laravel
      - ./laravel/vendor:/laravel/vendor
    depends_on:
      db:
        condition: service_healthy

  spa:
    build:
      context: ./spa
      dockerfile: Dockerfile.dev  
    volumes:
      - ./spa:/app                
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true                 

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.dev
    depends_on:
      - spa
      - php
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d/dev.default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./laravel/public:/laravel/public

volumes:
  mysqldata:
